SourceCode/Web/Areas/ThuTucArea/Controllers/ThuTucController.cs
using mojoportal.CoreHelpers;
using mojoportal.Service.CommonBusiness;
using mojoPortal.Business;
using mojoPortal.Model.Data;
using mojoPortal.Service.Business;
using mojoPortal.Service.CommonModel.BaoCao;
using mojoPortal.Service.CommonModel.ThuTuc;
using mojoPortal.Web.Areas.BaoCaoArea.Models;
using mojoPortal.Web.Areas.ThuTucArea.Models;
using mojoPortal.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace mojoPortal.Web.Areas.ThuTucArea.Controllers
{
    public class ThuTucController : BaseController
    {
        int dmLinhVucId = 0;
        string dmLinhVucCode = "DM_LINHVUC_THUTUC";

        int dmMucDoId = 0;
        string dmMucDoCode = WebConfigSettings.DM_MucDoDVC;

        int dmCapThuTucId = 0;
        string dmCapThuTuc = WebConfigSettings.DM_CapDoThuTuc;

        int dmDoiTuongThucHienId = 0;
        string dmDoiTuongThucHien = WebConfigSettings.DM_DoiTuongThucHien;
        

        int dmCachThucThucHienId = 0;
        string dmCachThucThucHien = WebConfigSettings.DM_CachThucThucHien;

        int dmCoQuanThucHienId = 0;
        string dmCoQuanThucHien = WebConfigSettings.DM_COQUANTHUCHIENDVC;


        public ThuTucController()
        {
            thuTucBieuMauBusiness = Get<ThuTucBieuMauBusiness>();
            thuTucBusiness = Get<ThuTucBusiness>();
            thuTucThanhPhanBusiness = Get<ThuTucThanhPhanBusiness>();

            categoryBusiness = Get<CategoryBusiness>();
            dmLinhVucId = categoryBusiness.GetByCode(dmLinhVucCode).ItemID;

            dmMucDoId = categoryBusiness.GetByCode(dmMucDoCode).ItemID;
            dmCapThuTucId = categoryBusiness.GetByCode(dmCapThuTuc).ItemID;
            dmDoiTuongThucHienId = categoryBusiness.GetByCode(dmDoiTuongThucHien).ItemID;
            dmCachThucThucHienId = categoryBusiness.GetByCode(dmCachThucThucHien).ItemID;

            dmCoQuanThucHienId = categoryBusiness.GetByCode(dmCoQuanThucHien).ItemID;
        }
        // GET: BaoCaoArea/BaoCaoArea
        public PartialViewResult FormThuTuc(int id = 0)
        {
            var listLinhVuc = new List<SelectListItem>();
            var listMucDoDVC = new List<SelectListItem>();
            var listDoiTuongThucHien = new List<SelectListItem>();
            var listCachThucThucHien = new List<SelectListItem>();
            var listCapThuTuc = new List<SelectListItem>();
            var listCoQuanThucHien = new List<SelectListItem>();


            ThuTucFormVM model = new ThuTucFormVM();
            if (id > 0)
            {
                var report = thuTucBusiness.GetByItemId(id);
                model = MapDataHelper<ThuTucFormVM,core_ThuTuc>.MapData(report);
                listLinhVuc = categoryBusiness.GetChild(dmLinhVucId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString(), Selected = (report.IdLinhVuc == x.ItemID) }).ToList();

                listMucDoDVC = categoryBusiness.GetChild(dmMucDoId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString(), Selected = (report.IdMucDo == x.ItemID) }).ToList();
                listDoiTuongThucHien = categoryBusiness.GetChild(dmDoiTuongThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString(), Selected = (report.IdDoiTuongThucHien == x.ItemID) }).ToList();
                listCachThucThucHien = categoryBusiness.GetChild(dmCachThucThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listCapThuTuc = categoryBusiness.GetChild(dmCapThuTucId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString(), Selected = (report.IdCapDoThuTuc == x.ItemID) }).ToList();

                listCoQuanThucHien = categoryBusiness.GetChild(dmCoQuanThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString(), Selected = (report.IdCoQuan == x.ItemID) }).ToList();

                model.ListThuTucBieuMau = thuTucBieuMauBusiness.GetList(id);
                model.ListThuTucThanhPhanHS = thuTucThanhPhanBusiness.GetList(id);
            }
            else
            {
                listLinhVuc = categoryBusiness.GetChild(dmLinhVucId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listMucDoDVC = categoryBusiness.GetChild(dmMucDoId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listDoiTuongThucHien = categoryBusiness.GetChild(dmDoiTuongThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listCachThucThucHien = categoryBusiness.GetChild(dmCachThucThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listCapThuTuc = categoryBusiness.GetChild(dmCapThuTucId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
                listCoQuanThucHien = categoryBusiness.GetChild(dmCoQuanThucHienId).Select(x => new SelectListItem { Text = x.Name, Value = x.ItemID.ToString() }).ToList();
            }
            model.ListLinhVuc = listLinhVuc;
            model.ListCachThucThucHien = listCachThucThucHien;
            model.ListDoiTuongThucHien = listDoiTuongThucHien;
            model.ListMucDoDVC = listMucDoDVC;
            model.ListCapThuTuc = listCapThuTuc;
            model.ListCoQuanThucHien = listCoQuanThucHien;

            return PartialView("_FormThuTuc", model);
        }

        public PartialViewResult AddThanhPhanHS()
        {
            return PartialView("_AddThanhPhanHoSo");
        }


        public PartialViewResult AddBieuMau()
        {
            return PartialView("_AddBieuMau");
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public JsonResult SaveForm(ThuTucFormVM model, FormCollection formCollection)
        {
            var result = new JsonResultBO(true);
            var report = new core_ThuTuc();
            try
            {
                result.Message = "Thêm mới thông tin thủ tục hành chính thành công";

                report = new core_ThuTuc();
                if (model.ItemID > 0)
                {
                    report = thuTucBusiness.GetByItemId(model.ItemID);
                    result.Message = "Cập nhật thông tin thủ tục hành chính thành công";
                }
                else
                {
                    report.CreatedBy = siteUser.Name;
                    report.CreatedByUser = siteUser.UserId;
                    report.CreatedDate = DateTime.Now;
                    report.SiteID = siteSettings.SiteId;
                }
                //get rewrite url product
                report = MaperData.Map<core_ThuTuc, ThuTucFormVM>(report, model);
                report.IsPublish = formCollection["IsPublish"].ToBooleanOnOff();
                string cachThucThucHien = string.Empty;
                if (!string.IsNullOrEmpty(formCollection["CachThucThucHien"]))
                {
                    cachThucThucHien = "," + formCollection["CachThucThucHien"];
                }
                report.CachThucThucHien = cachThucThucHien;
                thuTucBusiness.Save(report);

                //save thành phần hồ sơ
                if (model.TenGiayTo != null && model.TenGiayTo.Any())
                {
                    for (int i = 0; i < model.TenGiayTo.Length; i++)
                    {
                        core_ThuTuc_ThanhPhanHS thanhPhanHS = new core_ThuTuc_ThanhPhanHS();
                        thanhPhanHS.TenGiayTo = model.TenGiayTo[i];
                        thanhPhanHS.SoLuong = model.SoLuong[i];
                        thanhPhanHS.MauDonToKhai = model.MauDonToKhai[i];
                        thanhPhanHS.IdThuTuc = report.ItemID;
                        thuTucThanhPhanBusiness.Save(thanhPhanHS);
                    }
                }

                //save biểu mẫu
                if (model.TenMau != null && model.TenMau.Any())
                {
                    for (int i = 0; i < model.TenMau.Length; i++)
                    {
                        core_ThuTuc_BieuMau bieuMau = new core_ThuTuc_BieuMau();
                        bieuMau.IdThuTuc = report.ItemID;
                        bieuMau.PathFile = model.PathFile[i];
                        bieuMau.TenMau = model.TenMau[i];
                        thuTucBieuMauBusiness.Save(bieuMau);
                    }
                }
            }
            catch (Exception ex)
            {
                result.Message = "Không thể thực hiện thao tác này";
                result.Status = false;
            }
            return Json(result);
        }





        [HttpPost]
        public JsonResult DeleteThanhPhanHoSo(int id)
        {
            var result = new JsonResultBO(true);
            try
            {
                result.Message = "Xóa thành phần hồ sơ thành công";
                thuTucThanhPhanBusiness.Delete(id);
                thuTucThanhPhanBusiness.context.SaveChanges();
            }
            catch (Exception ex)
            {
                result.Message = "Không thực hiện được thao tác này";
                result.Status = false;
            }
            return Json(result);
        }


        [HttpPost]
        public JsonResult DeleteBieuMau(int id)
        {
            var result = new JsonResultBO(true);
            try
            {
                result.Message = "Xóa thành biểu mẫu thành công";
                thuTucBieuMauBusiness.Delete(id);
                thuTucBieuMauBusiness.context.SaveChanges();
            }
            catch (Exception ex)
            {
                result.Message = "Không thực hiện được thao tác này";
                result.Status = false;
            }
            return Json(result);
        }



        [HttpPost]
        public JsonResult Delete(int id)
        {

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/BaoCaoPublish.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.BaoCaoArea.Models
@model BaoCaoIndexVM
@{
    Layout = "~/Views/Shared/_LayoutAjax.cshtml";
    ViewBag.Title = "Quản lý công khai ngân sách";
    var groupData = Html.Raw(JsonConvert.SerializeObject(Model.ListData.ListItem));
}
<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2>@ViewBag.CategoryName</h2>
        </div>

        @Html.Partial("_SearchPublish")
        <div class="widge-t-body no-padding">
            <div id="tbl-BaoCao" class="hntbl-cover vanban_chung_box">
                <table class="hinet-table table table-striped table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="width30">STT</th>
                            <th>Tiêu đề</th>
                            <th>Năm/chu kỳ báo cáo</th>
                            <th>Biểu mẫu</th>
                            <th>Số QĐ công bố</th>
                            <th>Ngày công bố</th>
                            <th>Đường dẫn toàn văn</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="pd0 hienthi_vanban customize-hinet-table"></div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="total-page" value="@Model.ListData.TotalPage" />
<input type="hidden" id="total-record" value="@Model.ListData.Count" />
<script>
    var groupData = eval(@groupData);
</script>
<script src="~/Scripts/modules/report/report_publish.js"></script>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/Index.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.ThuTucArea.Models
@model ThuTucIndexVM
@{
    Layout = "~/Views/Shared/_LayoutAjaxEmpty.cshtml";
    ViewBag.Title = "Quản lý thủ tục hành chính";
    var groupData = Html.Raw(JsonConvert.SerializeObject(Model.ListData.ListItem));
}


<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2>Quản lý thủ tục hành chính</h2>
        </div>
        <div class="listvanban__box__thaotac wf100">
            <div class="rowthaotac__left listvanban__box__thaotac__row col-sm-6 pd0">
                <a href="#collapseDiv" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom collapsed" aria-controls="collapsePanel" data-toggle="collapse" role="button">
                    <i class="fa fa-search"></i>  <span>Tìm kiếm</span>
                </a>
                <a href="javascript:void(0)" onclick="onEdit(0)" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom" id="btn--add-new">
                    <i class="fa fa-plus"></i> <span>Thêm mới</span>
                </a>
            </div>
        </div>
        @Html.Partial("_SearchPartial")
        <div class="widge-t-body">
            <div id="tbl-ThuTuc" class="hntbl-cover vanban_chung_box">
                <table class="hinet-table table table-striped table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="width30">STT</th>
                            <th>Mã THHC</th>
                            <th>Mức độ DVC</th>
                            <th>Tên thủ tục hành chính</th>
                            <th>Lĩnh vực</th>
                            <th>Xuất bản</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="pd0 hienthi_vanban customize-hinet-table"></div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="total-page" value="@Model.ListData.TotalPage" />
<input type="hidden" id="total-record" value="@Model.ListData.Count" />
<script>
    var groupData = eval(@groupData);
</script>
<script src="~/Scripts/modules/thuTucHanhChinh/tchc_index.js"></script>
<script>
    function CreateUnit() {
        $.ajax({
            type: "get",
            url: "/ThuTucArea/ThuTuc/FormThuTuc",
            success: function (rs) {
                $("#globalModal").html(rs);
                $("#globalModal").modal("show");
            }, error: function (er) {
                console.log(er);
            }
        })
    }
</script>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_AddBieuMau.cshtml
<tr>
    <td>
        <input type="text" name="TenMau" class="form-control" />
    </td>
    <td>
        <input type="text" name="PathFile" class="form-control" style="width:calc(100% - 100px)" />
        <button type="button" class="btn btn-primary btn-sm" onclick="UploadBieuMau(this)"><i class="fa fa-upload" aria-hidden="true"></i></button>
    </td>
    <td></td>
    <td class="text-center">
        <div class='btn-group gr-nghiphep'>
            <a href="javascript:void(0)" onclick="onDeleteBieuMau(0,this)" class="btn-remove hvr-radial-out" title="Xóa"><i class="fa fa-trash"></i></a>
        </div>
    </td>
</tr>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_AddThanhPhanHoSo.cshtml
<tr>
    <td>
        <textarea class="form-control" name="TenGiayTo"></textarea>
    </td>
    <td>
        <textarea class="form-control" name="MauDonToKhai"></textarea>
    </td>
    <td>
        <textarea class="form-control" name="SoLuong"></textarea>
    </td>
    <td class="text-center">
        <div class='btn-group gr-nghiphep'>
            <a href="javascript:void(0)" onclick="onDeleteThanhPhanHoSo(0,this)" class="btn-remove hvr-radial-out" title="Xóa"><i class="fa fa-trash"></i></a>
        </div>
    </td>
</tr>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_ListBaoCao.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.BaoCaoArea.Models
@using mojoPortal.Model.Entities;
@model List<md_BaoCao>

@{
    var count = 0;
}


<p class="red">Tổng số báo cáo: @Model.Count()</p>

<div class="width100">

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>STT</th>
                <th>Tên báo cáo</th>
                <th>Năm, kỳ báo cáo</th>
                <th>Biểu mẫu</th>
                <th>Số quyết định công bố</th>
                <th>Ngày công bố</th>
                <th>Đường dẫn toàn văn</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.TenBaoCao</td>
                    <td>@item.NamChuKyBaoCao</td>
                    <td>@item.BieuMau</td>
                    <td>@item.SoQuyetDinhCongBo</td>
                    <td>@string.Format("{0:dd/MM/yyyy}", item.NgayCongBo)</td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.PathFile))
                        {
                            var listFile = item.PathFile.Split('?');
                            for (var i = 0; i < listFile.Count(); i++)
                            {
                                <p>
                                    <a href="@listFile[i]">
                                        @listFile[i].Split('/').LastOrDefault()
                                    </a>
                                </p>
                            }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_ListByLinhVuc.cshtml
@using mojoPortal.Web.Areas.BaoCaoArea.Models
@model BaoCaoListVM

<style>
    #content .tit {
        font-size: 20px;
        color: #2E83CB;
        text-transform: uppercase;
        border-bottom: 2px solid #2E83CB;
        padding-bottom: 5px;
    }
</style>
<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2 class="tit">@Model.Category.Name</h2>
        </div>
        <p class="width100">
            <hr />
        </p>
        <div class="widge-t-body no-padding">
            <div id="tbl-BaoCao" class="hntbl-cover vanban_chung_box">
                <table class="table table-bordered table-striped table-condensed" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="width30">STT</th>
                            <th>Tên báo cáo</th>
                            <th>Năm/chu kỳ báo cáo</th>
                            <th>Biểu mẫu</th>
                            <th>Số QĐ công bố</th>
                            <th>Ngày công bố</th>
                            <th>Đường dẫn toàn văn</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.ListBaoCao != null && Model.ListBaoCao.Any())
                        {
                            foreach (var item in Model.ListBaoCao)
                            {
                                <tr>
                                    <td>@(Model.ListBaoCao.IndexOf(item) + 1)</td>
                                    <td>@item.TenBaoCao</td>
                                    <td>@item.NamChuKyBaoCao</td>
                                    <td>@item.BieuMau</td>
                                    <td>@item.SoQuyetDinhCongBo</td>
                                    <td>@string.Format("{0:dd/MM/yyyy}", item.NgayCongBo)</td>
                              
                                    <td>
                                        @if (!string.IsNullOrEmpty(item.PathFile))
                                        {
                                            var listFile = item.PathFile.Split('?');
                                            foreach (var file in listFile)
                                            {
                                                <p>
                                                    <a href="@file">@item.TenBaoCao</a>
                                                </p>
                                            }
                                        }
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="7" class="text-danger">Chưa có báo cáo</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div class="width100 text-right">
                    <a href="@Model.Category.Description">Xem tiếp >></a>
                </div>
            </div>
        </div>
    </div>
</div>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_SearchPartial.cshtml
<style>
    .row-block {
        margin: 5px 0px;
        display: flex;
    }

    .txt-label {
        padding-top: 7px;
    }

    .width100 {
        width: 100% !important;
    }
</style>
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well">

        @using (Ajax.BeginForm("searchData", "ThuTuc",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "failure",
        OnSuccess = "searchSuccess",
    }, new { area = "ThuTucArea", id = "frmSearchThuTuc" }))
        {
            @Html.AntiForgeryToken()
            <div class="row row-block">
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Từ khóa</div>
                    <div class="col-md-8">
                        <input class="form-control width100" type="text" name="KeywordFillter" placeholder="Nhập Mã thủ tục hoặc Tên thủ tục để tra cứu" />
                    </div>

                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Cơ quan thực hiện</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdCoQuanFilter", (List<SelectListItem>)ViewBag.ListCoQuanThucHien, "--Chọn--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Lĩnh vực</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdLinhVucFillter", (List<SelectListItem>)ViewBag.ListLinhVuc, "--Chọn--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Mức độ DVC</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdMucDoDVCFillter", (List<SelectListItem>)ViewBag.ListMucDoDVC, "--Chọn--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Cách thức thực hiện</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdCachThucThucHienFilter", (List<SelectListItem>)ViewBag.ListCachThucThucHien, "--Chọn--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Đối tượng thực hiện</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdDoiTuongThucHien", (List<SelectListItem>)ViewBag.ListDoiTuongThucHien, "--Chọn--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-12 center" style=" margin-top:20px;">
                    <button id="btnSearch" type="button" onclick="SearchSubmit()" class="btn btn-labeled btn-primary">
                        <span class="btn-label">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </span>
                        Tìm kiếm
                    </button>

                    <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger">
                        <span class="btn-label"><i class="fa fa-sign-out" aria-hidden="true"></i></span>
                        Đóng
                    </a>
                </div>
            </div>

        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")
<script>
    function SearchSubmit() {
        $("#frmSearchThuTuc").submit();
    }
    function searchSuccess(rs) {
        $("#tbl-ThuTuc").hinetTable("data", {
            pageIndex: 1,
            pagecount: rs.TotalPage,
            recordCount: rs.Count,
            listItem: rs.ListItem,
        });
    }
    function pagefunctionSearch() {
        $(".txt-select2").select2();
    }
</script>

SourceCode/Web/Areas/ThuTucArea/Views/ThuTuc/_SearchPublish.cshtml
<style>
    .row-block {
        margin: 5px 0px;
    }

    .txt-label {
        padding-top: 7px;
    }

    .width100 {
        width: 100% !important;
    }

    .well {
        border-radius: 0;
        border: 0;
    }

    .panel-collapse {
        border: 1px solid #ddd;
    }
</style>
<div id="collapseDiv" class="panel-collapse" aria-expanded="false" role="tabpanel">
    <div class="well">

        @using (Ajax.BeginForm("searchPublish", "BaoCao",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "failure",
        OnSuccess = "searchSuccess",
    }, new { area = "BaoCaoArea", id = "frmSearchReport" }))
        {
            @Html.AntiForgeryToken()
            <div class="row row-block">
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Tiêu đề</div>
                    <div class="col-md-8">
                        <input class="form-control width100" type="text" name="QR_TEN_BAOCAO" />
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Năm/Chu kỳ báo cáo</div>
                    <div class="col-md-8">
                        <input class="form-control width100" type="number" name="QR_NAM_CHUKYBAOCAO" />
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Lĩnh vực</div>
                    <div class="col-md-8">
                        @Html.DropDownList("QR_LINHVUC", (List<SelectListItem>)ViewBag.ListLinhVuc, "--Lĩnh vực báo cáo--", new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Số QĐ công bố</div>
                    <div class="col-md-8">
                        <input class="form-control width100" type="text" name="QR_SOQD_CONGBO" />
                    </div>
                </div>
                <div class="col-md-12 center" style=" margin-top:20px;">
                    <button id="btnSearch" type="button" onclick="SearchSubmit()" class="btn btn-labeled btn-primary">
                        <span class="btn-label">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </span>
                        Tìm kiếm
                    </button>

                    <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger">
                        <span class="btn-label"><i class="fa fa-sign-out" aria-hidden="true"></i></span>
                        Đóng
                    </a>
                </div>
            </div>

        }
    </div>
</div>
@Scripts.Render("~/bundles/unobtrusive")
<script>
    function SearchSubmit() {
        $("#frmSearchReport").submit();
    }
    function searchSuccess(rs) {
        $("#tbl-BaoCao").hinetTable("data", {
            pageIndex: 1,
            pagecount: rs.TotalPage,
            recordCount: rs.Count,
            listItem: rs.ListItem,
        });
    }
    function pagefunctionSearch() {
        $(".txt-select2").select2();
    }
</script>