SourceCode/Web/Areas/OrganizationArea/Controllers/OrganizationController.cs
using mojoportal.CoreHelpers;
using mojoportal.Service.CommonBusiness;
using mojoPortal.Model.Data;
using mojoPortal.Service.Business;
using mojoPortal.Web.Areas.OrganizationArea.Models;
using mojoPortal.Web.Base;
using System;
using System.Web.Mvc;

namespace mojoPortal.Web.Areas.OrganizationArea.Controllers
{
    public class OrganizationController : BaseController
    {
        // GET: OrganizationArea/Organization
        public OrganizationController()
        {
            core_CCTC_DepartmentBusiness = Get<core_CCTC_DepartmentBusiness>();
            core_CCTC_LeaderBusiness = Get<core_CCTC_LeaderBusiness>();
            core_CTTCBusiness = Get<core_CTTCBusiness>();
        }
        public ActionResult Index(int siteId = 1)
        {
            OrganizationFormVM model = new OrganizationFormVM();
            var organization = core_CTTCBusiness.GetBySite(siteId);
            model = MaperData.Map<OrganizationFormVM, core_CCTC>(model, organization);
            model.ListDepartment = core_CCTC_DepartmentBusiness.GetListBy(model.ItemID);
            model.ListLeader = core_CCTC_LeaderBusiness.GetListBy(model.ItemID);
            return View(model);
        }
        [AllowAnonymous]
        public ActionResult OrganizationPublish(int siteId = 1)
        {
            OrganizationPublishVM model = new OrganizationPublishVM();
            model.core_CCTC = core_CTTCBusiness.GetBySite(siteId);
            model.ListDepartment = core_CCTC_DepartmentBusiness.GetListBy(model.core_CCTC.ItemID);
            model.ListLeader = core_CCTC_LeaderBusiness.GetListBy(model.core_CCTC.ItemID);
            var isMobileDevice = SiteUtils.IsMobileDevice();
            if (isMobileDevice == true)
            {
                return View("OrganizationPublishMobie", model);
            }
            else
            {
                return View("OrganizationPublish", model);
            }
        }

        [HttpPost]
        public JsonResult SaveOrganization(OrganizationFormVM model, FormCollection formCollection)
        {
            var result = new JsonResultBO(true);
            try
            {
                var oke = formCollection["TitleBoxLanhDao"];
                var organization = new core_CCTC();
                if (model.ItemID > 0)
                {
                    organization = core_CTTCBusiness.FindIfNull(model.ItemID);
                    organization.EditedBy = siteUser.UserId;
                    organization.EditedDate = DateTime.Now;
                }
                else
                {
                    organization.CreatedBy = siteUser.Name;
                    organization.CreatedByUser = siteUser.UserId;
                    organization.CreatedDate = DateTime.Now;
                    organization.SiteID = 1;
                }
                organization = MaperData.Map<core_CCTC, OrganizationFormVM>(organization, model);

                core_CTTCBusiness.Save(organization);
            }
            catch
            {

                result.Status = false;
            }

            return Json(result);
        }

        public PartialViewResult FormLeader(int cctcId = 0, int id = 0)
        {
            var leader = new LeaderFormVM();
            if (id > 0)
            {
                var search_leader = core_CCTC_LeaderBusiness.Find(id);
                if (search_leader != null)
                {
                    leader = MaperData.Map<LeaderFormVM, core_CCTC_Leader>(leader, search_leader);
                }
            }
            leader.CCTC_ID = cctcId;
            return PartialView("_FormLeader", leader);
        }
        [HttpPost]
        public JsonResult SaveLeader(LeaderFormVM model)
        {
            var result = new JsonResultBO(true);
            result.Message = "Thêm mới lãnh đạo thành công";
            try
            {
                var leader = new core_CCTC_Leader();
                if (model.ItemID > 0)
                {
                    result.Message = "Cập nhật lãnh đạo thành công";
                    var search = core_CCTC_LeaderBusiness.Find(model.ItemID);
                    if (search != null)
                    {
                        leader = search;
                    }
                }
                leader = MaperData.Map<core_CCTC_Leader, LeaderFormVM>(leader, model);
                leader.PathIMG = model.PathIMG;
                core_CCTC_LeaderBusiness.Save(leader);
            }
            catch
            {
                result.Message = "Không thể thực hiện thao tác này";
                result.Status = false;
            }

            return Json(result);
        }
        public PartialViewResult TableLeader(int cctcId = 0)
        {
            var result = core_CCTC_LeaderBusiness.GetListBy(cctcId);

            return PartialView("_TableLeader", result);
        }
        public PartialViewResult TableDepartment(int cctcId = 0)
        {
            var result = core_CCTC_DepartmentBusiness.GetListBy(cctcId);

            return PartialView("_TableDepartment", result);
        }

        public PartialViewResult FormDepartment(int cctcId = 0, int id = 0)
        {
            var department = new DepartmentFormVM();
            ViewBag.ListLeader = core_CCTC_LeaderBusiness.GetChildItem();
            if (id > 0)
            {
                var search_department = core_CCTC_DepartmentBusiness.Find(id);
                if (search_department != null)
                {
                    department = MaperData.Map<DepartmentFormVM, core_CCTC_Department>(department, search_department);
                }
            }
            department.CCTC_ID = cctcId;
            return PartialView("_FormDepartment", department);
        }
        [HttpPost]
        public JsonResult SaveDepartment(DepartmentFormVM model)
        {
            var result = new JsonResultBO(true);
            result.Message = "Thêm mới phòng ban thành công";
            try
            {
                var department = new core_CCTC_Department();
                if (model.ItemID > 0)
                {
                    result.Message = "Cập nhật phòng ban thành công";
                    var search = core_CCTC_DepartmentBusiness.Find(model.ItemID);
                    if (search != null)
                    {
                        department = search;
                    }
                }
                department = MaperData.Map<core_CCTC_Department, DepartmentFormVM>(department, model);

                core_CCTC_DepartmentBusiness.Save(department);
            }
            catch
            {
                result.Message = "Không thể thực hiện thao tác này";
                result.Status = false;
            }

            return Json(result);
        }

        [HttpPost]
        public JsonResult DeleteLeader(int id = 0)
        {
            var result = new JsonResultBO(true);
            if (id > 0)
            {
                core_CCTC_LeaderBusiness.Delete(id);
                core_CCTC_LeaderBusiness.context.SaveChanges();
            }
            return Json(result);
        }
        [HttpPost]
        public JsonResult DeleteDepartment(int id = 0)
        {
            var result = new JsonResultBO(true);
            if (id > 0)
            {
                core_CCTC_DepartmentBusiness.Delete(id);
                core_CCTC_DepartmentBusiness.context.SaveChanges();
            }
            return Json(result);
        }
    }
}

SourceCode/Web/Areas/OrganizationArea/Views/Organization/Index.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.OrganizationArea.Models
@model OrganizationFormVM
@{
    Layout = "~/Views/Shared/_LayoutAjax.cshtml";
}
<style>
</style>
<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2>Cập nhật thông tin cơ cấu tổ chức</h2>
        </div>
        @using (
Ajax.BeginForm("SaveOrganization", "Organization",
new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxSucces", OnFailure = "AjaxError" },
new { @class = "", id = "frmOrganization", area = "OrganizationArea" }))
        {
            @Html.HiddenFor(x=>x.ItemID)
        <div class="widge-t-body no-padding">
            <div class="form-organization form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-3">Tiêu đề khối thông tin lãnh đạo<span class="red">*</span></label>
                    <div class="col-sm-9">
                        @Html.TextAreaFor(x => x.TitleBoxLanhDao, new { @class = "form-control", @rowspan = "3" })
                        @Html.ValidationMessageFor(x => x.TitleBoxLanhDao)

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">Tiêu đề khối thông tin phòng ban <span class="red">*</span></label>
                    <div class="col-sm-9">
                        @Html.TextAreaFor(x => x.TitleBoxPhongBan, new { @class = "form-control", @rowspan = "3" })
                        @Html.ValidationMessageFor(x => x.TitleBoxPhongBan)
                    </div>
                </div>
            </div>
            @if (Model.ItemID > 0)
            {
                <div class="col-sm-12 text-right" style="padding: 0;margin: 10px 0;">
                    <button class="btn btn-primary" type="button" onclick="FormLeader(0)">Thêm mới lãnh đạo</button>
                </div>
                <div class="form-leader" id="tblLeader">
                    @Html.Partial("_TableLeader",Model.ListLeader)
                </div>
                <div class="col-sm-12 text-right" style="padding: 0;margin: 10px 0;">
                    <button class="btn btn-primary" type="button" onclick="FormDepartment(0)">Thêm mới phòng ban</button>
                </div>
                <div class="form-department" id="tblDepartment">
                    @Html.Partial("_TableDepartment",Model.ListDepartment)
                </div>
            }
            <div class="col-sm-12 text-center form-group">
                <button class="btn-success btn" type="button" onclick="SubmitOrganization()">Cập nhật</button>
            </div>
        </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")
<script>
    function SubmitOrganization() {
        var checkSubmit = jQuery('#frmOrganization').valid();
        if (checkSubmit) {
            $("#frmOrganization").submit();
        }
    }
    function FormLeader(id) {
        OpenGlobalModal("get", "/OrganizationArea/Organization/FormLeader", { cctcId:@Model.ItemID, id: id }, true);
    }
        function FormDepartment(id) {
            OpenGlobalModal("get", "/OrganizationArea/Organization/FormDepartment", { cctcId:@Model.ItemID, id: id }, true);
    }

    function ajaxSucces(rs) {
        if (rs.Status) {
            NotifySuccess("Cập nhật thông tin cơ cấu tổ chức thành công");
        } else {
            NotifyError("Không thể thực hiện thao tác này");
        }
    }

    function reloadTableLeader() {
        CallAjaxLoading("get", "/OrganizationArea/Organization/TableLeader?cctcId=@Model.ItemID", null, true, function (rs) {
            $("#tblLeader").html(rs);
        });
    }
    function reloadTableDepartment() {
        CallAjaxLoading("get", "/OrganizationArea/Organization/TableDepartment?cctcId=@Model.ItemID", null, true, function (rs) {
            $("#tblDepartment").html(rs);
        });
    }
</script>
<script src="~/Scripts/modules/organization/organization_index.js"></script>

SourceCode/Web/Areas/OrganizationArea/Views/Organization/OrganizationPublish.cshtml
@using mojoPortal.Web.Areas.OrganizationArea.Models
@model OrganizationPublishVM
<div class="width100" style="margin-bottom: 20px;">

    <h1 style="text-align: center; margin: 40px 0; font-size:31px">@Model.core_CCTC.TitleBoxLanhDao</h1>
    <div class="bg-cocautochuc">
        @if (Model.ListLeader != null && Model.ListLeader.Any())
        {
            var boss = Model.ListLeader.FirstOrDefault();
            <div class="col-sm-12" style="margin-bottom: 75px">
                <div class="col-sm-4">&nbsp;</div>

                <div class="col-sm-4" style="text-align: center;padding: 10px">
                    @if (!string.IsNullOrEmpty(boss.PathIMG))
                    {
                        <a href="@boss.LinkDetail">
                            <img alt="" src="@boss.PathIMG" style="width: 200px; margin-bottom: 15px; height: 235px; " />
                        </a>
                    }
                    else
                    {
                        <div style="width: 200px; margin-bottom: 20px; height: 235px; " />
                    }
                    <p style="font-weight: bold; text-transform: uppercase; color: #333333"><a href="@boss.LinkDetail">@string.Format("{0} : {1}", boss.ChucVu, boss.Title)</a></p>
                </div>

                <div class="col-sm-4">&nbsp;</div>
            </div>
            <div class="col-sm-12">

                @if (Model.ListLeader.Count > 1)
                {

                    var listData = Model.ListLeader.Skip(1).ToList();
                    foreach (var item in listData)
                    {
                        <div class="col-sm-4">
                            <div style="text-align: center;padding: 10px">
                                @if (!string.IsNullOrEmpty(item.PathIMG))
                                {
                                    <a href="@item.LinkDetail">
                                        <img alt="" src="@item.PathIMG" style="width: 200px; margin-bottom: 15px; height: 180px;"  />
                                    </a>
                                }
                                else
                                {
                                    <div style="width: 100%; margin-bottom: 20px; height: 180px; width: auto " />
                                }
                                <p style="font-weight: bold; text-transform: uppercase; margin-bottom:5px">@item.ChucVu :</p>
                                <p style="font-weight: bold; text-transform:uppercase;color: #333333"><a href="@item.LinkDetail">@item.Title</a></p>
                            </div>
                        </div>
                    }
                }
            </div>

        }
        else
        {

            <h4 style="text-align: center; margin: 10px 0; color: #ce1127;width: 100%;float: left;">
                (ĐANG CẬP NHẬT)
            </h4>
        }

        <div style=" margin-bottom: 30px; width: 100%;float: left;">
            @*<h2 style="text-align: center; margin: 40px 0 0;width: 100%;float: left;">
                    @Model.core_CCTC.TitleBoxPhongBan
                </h2>*@
            @if (Model.ListDepartment != null && Model.ListDepartment.Any())
            {
                <div class="department">

                    @foreach (var item in Model.ListDepartment)
                    {
                        <a href="@item.LinkDetail">
                            <div class="col-sm-6 name-department">@item.Name</div>
                        </a>
                    }
                </div>
            }
            else
            {
                <h4 style="text-align: center; margin: 10px 0; color: #ce1127;width: 100%;float: left;">
                    (ĐANG CẬP NHẬT)
                </h4>
            }
        </div>
    </div>
</div>

<style>
    .bg-cocautochuc {
        background-image: url('../../../../Data/Sites/1/skins/framework/ImgCucTTDLV2/bngxx.png');
        background-position: center;
        background-repeat: no-repeat;
        width: 100%;
        float: left;
        height: 1095px;
    }

    .name-department {
        font-weight: bold;
        margin-bottom: 70px;
        color: #333333;
        font-size: 16px;
    }

    .department {
        width: 1000px;
        /*margin: 0 auto;*/
        float: right;
        padding-top: 115px;
    }

        .department ul {
            float: left;
            margin-top: 30px;
        }

            .department ul li {
                font-size: 15px;
                padding: 10px;
            }
</style>

SourceCode/Web/Areas/OrganizationArea/Views/Organization/OrganizationPublishMobie.cshtml
@using mojoPortal.Web.Areas.OrganizationArea.Models
@model OrganizationPublishVM
<div class="width100" style="margin-bottom: 20px;">

    <h1 style="text-align: center; margin: 40px 0">@Model.core_CCTC.TitleBoxLanhDao</h1>
    @if (Model.ListLeader != null && Model.ListLeader.Any())
    {
        <div class="col-sm-12">
            @if (Model.ListLeader.Count > 1)
            {

                foreach (var item in Model.ListLeader)
                {
                    <div class="col-sm-12" style="width: 100%; float: left; border-bottom: 1px dotted; margin-bottom: 20px;">
                        <div style="text-align: center;padding: 10px; border-radius: 5px;box-shadow: 0 0 10px 0 #ccc">
                            @if (!string.IsNullOrEmpty(item.PathIMG))
                            {
                                <a href="@item.LinkDetail">
                                    <img alt="" src="@item.PathIMG" style="width: 100%; margin-bottom: 15px; height: 180px; width: auto" />
                                </a>
                            }
                            else
                            {
                                <div style="width: 100%; margin-bottom: 20px; height: 180px; width: auto " />
                            }
                          
                                <p style="font-weight: bold; text-transform: uppercase; margin-bottom:5px">@item.ChucVu :</p>
                                <p style="font-weight: bold; text-transform:uppercase"><a style="color: #333333;" href="@item.LinkDetail">@item.Title</a></p>
                        </div>
                        @if (Model.ListDepartment != null && Model.ListDepartment.Any())
                        {
                            var ListDepartment = Model.ListDepartment.Where(x => x.CCTC_Leader_ID == item.ItemID);
                            <div class="department">
                                <h4 style="text-align: center; width: 100%; float: left; margin-top: 25px">
                                    @Model.core_CCTC.TitleBoxPhongBan
                                </h4>
                                <ul style="width:100%; float: left">
                                    @foreach (var itemdp in ListDepartment)
                                    {
                                        <li class="name-department"><a href="@itemdp.LinkDetail"> @itemdp.Name</a></li>
                                    }
                                </ul>
                            </div>
                        }
                    </div>
                }
            }
        </div>

    }
    else
    {

        <h4 style="text-align: center; margin: 10px 0; color: #ce1127;width: 100%;float: left;">
            (ĐANG CẬP NHẬT)
        </h4>
    }
</div>

<style>

    .name-department a {
        color: #333333;
    }
    .name-department {
        font-weight: bold;
        margin-bottom: 10px;

    }

    .department {
    }

        .department ul {
            float: left;
        }

            .department ul li {
                font-size: 15px;
                padding: 10px;
            }
</style>

SourceCode/Web/Areas/OrganizationArea/Views/Organization/_FormDepartment.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.OrganizationArea.Models
@model DepartmentFormVM
@{

    var title = "Thêm mới phòng ban";
    if (Model.ItemID > 0)
    {
        title = "Cập nhật phòng";
    }
    var ListLeader = ViewBag.ListLeader as List<SelectListItem>;
}
@using (
Ajax.BeginForm("SaveDepartment", "Organization",
new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxDepartmentSucces", OnFailure = "AjaxError" },
new { @class = "", id = "frmDepartment", area = "OrganizationArea" }))
{
    @Html.HiddenFor(x => x.ItemID)
    @Html.HiddenFor(x => x.CCTC_ID)

    <div class="modal-dialog" style="width:80%; min-width:850px">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">@title</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Họ tên<span class="red">*</span></label>
                        <div class="col-sm-9">
                            @Html.DropDownList("CCTC_Leader_ID", ListLeader, "--Lĩnh Lãnh đạo--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Name)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Phòng ban<span class="red">*</span></label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Name)

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Url</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.LinkDetail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.LinkDetail)
                        </div>
                    </div> 
                    <div class="form-group">
                        <label class="control-label col-sm-3">Thứ tự hiển thị</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.OrderBy, new { @class = "form-control", @type = "number" })
                            @Html.ValidationMessageFor(x => x.OrderBy)
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer center boder-box">
                <button type="button" onclick="SubmitFormDepartment()" class="btn btn-primary">Hoàn thành</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-sign-out" aria-hidden="true"></i> <span>Đóng</span>
                </button>
            </div>
        </div>
    </div>
}
@*@Scripts.Render("~/bundles/jqueryval")*@

<script>
   
    function AjaxError(er) {
        console.log(er.Message);
    }
    function SubmitFormDepartment() {
        var checkSubmit = jQuery('#frmDepartment').valid();
        if (checkSubmit) {

            $("#frmDepartment").submit();
        }
    }

    function ajaxDepartmentSucces(rs) {
        if (rs.Status == true) {
            NotifySuccess(rs.Message);
            CloseGlobalModal();
            reloadTableDepartment();
        } else {
            NotifyError(rs.Message);
        }
    }


</script>

SourceCode/Web/Areas/OrganizationArea/Views/Organization/_FormLeader.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.OrganizationArea.Models
@model LeaderFormVM
@{

    var title = "Thêm mới lãnh đạo";
    if (Model.ItemID > 0)
    {
        title = "Cập nhật lãnh đạo";
    }
}
@using (
Ajax.BeginForm("SaveLeader", "Organization",
new AjaxOptions { HttpMethod = "POST", OnSuccess = "ajaxLeaderSucces", OnFailure = "AjaxError" },
new { @class = "", id = "frmLeader", area = "OrganizationArea" }))
{
    @Html.HiddenFor(x => x.ItemID)
    @Html.HiddenFor(x => x.CCTC_ID)

    <div class="modal-dialog" style="width:80%; min-width:850px">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">@title</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-3">Họ tên<span class="red">*</span></label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Title)

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Chức vụ <span class="red">*</span></label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.ChucVu, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.ChucVu)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Hình ảnh</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.PathIMG, new { @class = "form-control", @style = "width:calc(100% - 100px)" })
                            &nbsp;
                            <button type="button" class="btn btn-default" onclick="GetUrlImage()"><i class="fa fa-folder-open" aria-hidden="true"></i></button>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Email</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Email)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Số điện thoại</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Phone)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Url</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.LinkDetail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.LinkDetail)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Thứ tự hiển thị</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.OrderBy, new { @class = "form-control",@type="number" })
                            @Html.ValidationMessageFor(x => x.OrderBy)
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer center boder-box">
                <button type="button" onclick="SubmitFormLeader()" class="btn btn-primary">Hoàn thành</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-sign-out" aria-hidden="true"></i> <span>Đóng</span>
                </button>
            </div>
        </div>
    </div>
}
@*@Scripts.Render("~/bundles/jqueryval")*@

<script>
    function GetUrlImage() {
        var finder = new CKFinder();
        finder.inPopup = true;
        finder.defaultLanguage = 'vi';
        finder.language = 'vi';
        finder.popupFeatures = "width=900,height=900,menubar=yes,toolbar=no,modal=yes";
        finder.selectMultiple = true;
        finder.startupPath = "Files:/";
        finder.BaseUrl = "/Files/";
        finder.resourceType = 'Files';
        finder.selectActionFunction = function (fileUrl, data, allFiles) {
            $("#PathIMG").val(fileUrl);
            //$("#viewVideo").empty();
            //$("#viewVideo").append("<img src='" + fileUrl + "' width='200'/>");
            //$("#PathFile").change();
        };
        finder.popup();
    }
    function AjaxError(er) {
        console.log(er.Message);
    }
    function SubmitFormLeader() {
        var checkSubmit = jQuery('#frmLeader').valid();
        if (checkSubmit) {

            $("#frmLeader").submit();
        }
    }

    function ajaxLeaderSucces(rs) {
        if (rs.Status == true) {
            NotifySuccess(rs.Message);
            CloseGlobalModal();
            reloadTableLeader();
        } else {
            NotifyError(rs.Message);
        }
    }


</script>

SourceCode/Web/Areas/OrganizationArea/Views/Organization/_TableDepartment.cshtml
@using mojoPortal.Model.Entities
@model List<core_CCTC_Department>
<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr>
            <th>STT</th>
            <th>Phòng/Ban</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@(Model.IndexOf(item) + 1)</td>

                    <td>@item.Name</td>
                    <td>
                        <div class='btn-group gr-nghiphep'>
                            <a href="javascript:FormDepartment(@item.ItemID)" class="btn-edit hvr-radial-out" data-id="10595" title="Chỉnh sửa"><i class="fa fa-pencil-square fa-lg"></i></a>
                            <a href="javascript:void(0)" onclick="onDeleteDepartment(@item.ItemID, this)" class="btn-remove hvr-radial-out" data-id="@item.ItemID" data-object-name="@item.Name" title="Xóa"><i class="fa fa-trash"></i></a>
                        </div>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3" class="text-danger font-weight-bold">Chưa có thông tin</td>
            </tr>
        }
    </tbody>
</table>