SourceCode/Web/Areas/QLLichLamViecArea/Controllers/QLLichLamViecController.cs
using mojoportal.CoreHelpers;
using mojoportal.Service.CommonBusiness;
using mojoportal.Service.UoW;
using mojoPortal.Model.Data;
using mojoPortal.Service.CommonModel.BaoCao;
using mojoPortal.Service.CommonModel.LichCongTac;
using mojoPortal.Service.CommonModel.LichLamViec;
using mojoPortal.Web.Areas.QL_LichCongTacArea.Models;
using mojoPortal.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mojoPortal.Web.Areas.QLLichLamViecArea.Controllers
{
    public class QLLichLamViecController : BaseController
    {
        // GET: QLLichLamViecArea/QLLichLamViec
        string searchKey = "searchLichLamViecModel";
        public QLLichLamViecController()
        {
            var unitOfwork = new UnitOfWork();
            lichLamViecBusiness = new Service.Business.LichLamViecBusiness(unitOfwork);
            categoryBusiness = new Service.Business.CategoryBusiness(unitOfwork);
        }
        public ActionResult Index()
        {

            var listData = lichLamViecBusiness.GetDaTaByPage(null);
            SessionManager.SetValue(searchKey, null);
            ViewBag.ListLanhDao = categoryBusiness.GetListChildSelectItem(WebConfigSettings.DM_LANHDAO);

            return View(listData);
        }

        [HttpPost]
        public JsonResult getData(int indexPage, string sortQuery, int pageSize)
        {
            var searchModel = SessionManager.GetValue(searchKey) as LichLamViecSearchDto;
            if (!string.IsNullOrEmpty(sortQuery))
            {
                if (searchModel == null)
                {
                    searchModel = new LichLamViecSearchDto();
                }
                searchModel.sortQuery = sortQuery;
                if (pageSize > 0)
                {
                    searchModel.pageSize = pageSize;
                }
                SessionManager.SetValue(searchKey, searchModel);
            }
            var data = lichLamViecBusiness.GetDaTaByPage(searchModel, indexPage, pageSize);
            return Json(data);
        }
        public PartialViewResult Create()
        {
            var myModel = new CreateVM();
            myModel.ListThanhPhanThamDu = categoryBusiness.GetListChildSelectItem(WebConfigSettings.DM_LANHDAO);
            var currentTime = DateTime.Now;
            myModel.ListDropdownGio = GetHours(currentTime.Hour);

            myModel.ListDropdownPhut = GetMinutes(0);
            return PartialView("_CreatePartial", myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Create(CreateVM model, FormCollection formCollection)
        {
            var result = new JsonResultBO(true, "Tạo mới lịch công tác thành công");
            try
            {
                var entity = new core_LichLamViec();
                entity = MaperData.Map<core_LichLamViec, CreateVM>(entity, model);
                if (entity.NgayLamViec.HasValue)
                {
                    var thoiGianLamViec = entity.NgayLamViec.Value.AddHours(model.Gio).AddMinutes(model.Phut);
                    entity.ThoiGianLamViec = thoiGianLamViec;
                }
                entity.IsPublish = formCollection["IsPublish"].ToBooleanOnOff();
                if (model.ThanhPhanThamDuArray != null && model.ThanhPhanThamDuArray.Any())
                {
                    entity.ThanhPhanThamDu = string.Join(" ", model.ThanhPhanThamDuArray);
                }
                entity.CreatedBy = siteUser.Name;
                entity.CreatedByUser = siteUser.UserId;
                entity.CreatedDate = DateTime.Now;
                lichLamViecBusiness.Save(entity);
            }
            catch (Exception ex)
            {
                result.MessageFail(ex.Message);
            }
            return Json(result);
        }

        public PartialViewResult Edit(long id)
        {
            var myModel = new EditVM();

            var obj = lichLamViecBusiness.Find(id);
            if (obj == null)
            {
                throw new HttpException(404, "Không tìm thấy thông tin");
            }
            myModel = MapDataHelper<EditVM, core_LichLamViec>.MapData(obj);
            var hour = 0;
            var minute = 0;
            if (obj.ThoiGianLamViec.HasValue)
            {
                hour = obj.ThoiGianLamViec.Value.Hour;
                minute = obj.ThoiGianLamViec.Value.Minute;
            }
            myModel.Gio = hour;
            myModel.Phut = minute;
            myModel.ListThanhPhanThamDu = categoryBusiness.GetListChildSelectItem(WebConfigSettings.DM_LANHDAO);
            myModel.ListDropdownGio = GetHours(hour);
            myModel.ListDropdownPhut = GetMinutes(minute);

            return PartialView("_EditPartial", myModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Edit(EditVM model, FormCollection formCollection)
        {
            var result = new JsonResultBO(true);
            try
            {
                var itemId = formCollection["ItemID"];
                var obj = lichLamViecBusiness.Find(model.ItemID);
                if (obj == null)
                {
                    throw new Exception("Không tìm thấy thông tin");
                }
                var entity = new core_LichLamViec();
                entity = MaperData.Map<core_LichLamViec, EditVM>(obj, model);
                if (entity.NgayLamViec.HasValue)
                {
                    var thoiGianLamViec = entity.NgayLamViec.Value.AddHours(model.Gio).AddMinutes(model.Phut);
                    entity.ThoiGianLamViec = thoiGianLamViec;
                }
                if (model.ThanhPhanThamDuArray != null && model.ThanhPhanThamDuArray.Any())
                {
                    entity.ThanhPhanThamDu = string.Join(" ", model.ThanhPhanThamDuArray);
                }
                entity.EditedBy = siteUser.UserId;
                entity.EditedDate = DateTime.Now;
                entity.IsPublish = formCollection["IsPublish"].ToBooleanOnOff();
                lichLamViecBusiness.Save(entity);

            }
            catch (Exception ex)
            {
                result.Status = false;
                result.Message = "Không cập nhật được";
            }
            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult searchData(LichLamViecSearchDto searchModel)
        {
            if (searchModel == null)
            {
                searchModel = new LichLamViecSearchDto();
                searchModel.pageSize = 20;
            }

            SessionManager.SetValue((searchKey), searchModel);

            var data = lichLamViecBusiness.GetDaTaByPage(searchModel, 1, searchModel.pageSize);
            return Json(data);
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            var result = new JsonResultBO(true, "Xóa Quản lý lịch công tác thành công");
            try
            {
                var user = lichLamViecBusiness.Find(id);
                if (user == null)
                {
                    throw new Exception("Không tìm thấy thông tin để xóa");
                }
                lichLamViecBusiness.Delete(id);
                lichLamViecBusiness.context.SaveChanges();
            }
            catch (Exception ex)
            {
                result.MessageFail("Không thực hiện được");
            }
            return Json(result);
        }

        private List<SelectListItem> GetHours(int? selected = 1)
        {
            var result = new List<SelectListItem>();
            for (int i = 0; i < 24; i++)
            {
                result.Add(new SelectListItem()
                {
                    Text = i + " giờ",
                    Value = i.ToString(),
                    Selected = selected == i
                });
            }

            return result;
        }

        private List<SelectListItem> GetMinutes(int? selected = 1)
        {
            var result = new List<SelectListItem>();
            for (int i = 0; i < 60; i++)
            {
                result.Add(new SelectListItem()
                {
                    Text = i + " phút",
                    Value = i.ToString(),
                    Selected = selected == i
                });
            }

            return result;
        }


        public ActionResult Detail(long id)
        {
            var model = new DetailVM();
            model.objInfo = lichLamViecBusiness.GetDetail(id);
            return View(model);
        }
        //[PermissionAccess(Code = permissionImport)]

        //public FileResult ExportExcel()
        //{
        //    var searchModel = SessionManager.GetValue(searchKey) as QL_LichCongTacSearchDto;
        //    var data = _QL_LichCongTacService.GetDaTaByPage(searchModel).ListItem;
        //    var dataExport = _mapper.Map<List<QL_LichCongTacExportDto>>(data);
        //    var fileExcel = ExportExcelV2Helper.Export<QL_LichCongTacExportDto>(dataExport);
        //    return File(fileExcel, "application/octet-stream", "QL_LichCongTac.xlsx");
        //}

        //[PermissionAccess(Code = permissionImport)]
        //public ActionResult Import()
        //{
        //    var model = new ImportVM();
        //    model.PathTemplate = Path.Combine(@"/Uploads", WebConfigurationManager.AppSettings["IMPORT_QL_LichCongTac"]);

        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult CheckImport(FormCollection collection, HttpPostedFileBase fileImport)
        //{
        //    JsonResultImportBO<QL_LichCongTacImportDto> result = new JsonResultImportBO<QL_LichCongTacImportDto>(true);
        //    //Kiểm tra file có tồn tại k?
        //    if (fileImport == null)
        //    {
        //        result.Status = false;
        //        result.Message = "Không có file đọc dữ liệu";

SourceCode/Web/Areas/QLLichLamViecArea/Views/QLLichLamViec/Detail.cshtml
@{
    ViewBag.Title = "Quản lý lịch công tác";
    Layout = "~/Views/Shared/_LayoutAce.cshtml";
    ViewBag.ModuleName = "Quản lý Quản lý lịch công tác";
    ViewBag.PageName = "Thông tin Quản lý lịch công tác";
    ViewBag.ModuleCode = "QL_LichCongTac_detail";
}
@using Hinet.Model.IdentityEntities
@using Hinet.Model.Entities
@using Hinet.Web.Areas.QL_LichCongTacArea.Models

@model DetailVM
@section ActionBarRight{
    <a href="/QL_LichCongTacArea/QL_LichCongTac/Index" class="btn btn-primary btn-sm"><i class="fa fa-reply" aria-hidden="true"></i> Quay lại</a>
}

<div class="row">
     <div class="col-sm-12">
           <table class="table-info">
           	
<tr><td>Nhân sự</td><td>@Model.objInfo.IdUser</td></tr>
<tr><td>Ngày làm việc</td><td>@Model.objInfo.NgayLamViec</td></tr>
<tr><td>Giờ bắt đầu</td><td>@Model.objInfo.GioBatDau</td></tr>
<tr><td>Giờ kết thúc</td><td>@Model.objInfo.GioKetThuc</td></tr>
<tr><td>Ghi chú</td><td>@Model.objInfo.GhiChu</td></tr>
<tr><td></td><td>@Model.objInfo.CreatedDate</td></tr>
<tr><td></td><td>@Model.objInfo.CreatedBy</td></tr>
<tr><td></td><td>@Model.objInfo.CreatedID</td></tr>
<tr><td></td><td>@Model.objInfo.UpdatedDate</td></tr>
<tr><td></td><td>@Model.objInfo.UpdatedBy</td></tr>
<tr><td></td><td>@Model.objInfo.UpdatedID</td></tr>
<tr><td></td><td>@Model.objInfo.IsDelete</td></tr>
<tr><td></td><td>@Model.objInfo.DeleteTime</td></tr>
<tr><td></td><td>@Model.objInfo.DeleteId</td></tr>

           </table>
     </div>
    
</div>

<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

SourceCode/Web/Areas/QLLichLamViecArea/Views/QLLichLamViec/Index.cshtml
@using Newtonsoft.Json
@using mojoPortal.Service.Business
@using mojoportal.Service.CommonBusiness
@using mojoPortal.Service.CommonModel.LichCongTac
@model PageListResultBO<LichLamViecDto>

@{
    Layout = "~/Views/Shared/_LayoutAjaxEmpty.cshtml";
    ViewBag.Title = "Quản lý lịch công tác";
    var groupData = Html.Raw(JsonConvert.SerializeObject(Model.ListItem));
}


<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2>Quản lý lịch công tác</h2>
        </div>
        <div class="listvanban__box__thaotac wf100">
            <div class="rowthaotac__left listvanban__box__thaotac__row col-sm-6 pd0">
                <a href="#collapseDiv" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom collapsed" aria-controls="collapsePanel" data-toggle="collapse" role="button">
                    <i class="fa fa-search"></i>  <span>Tìm kiếm</span>
                </a>
                <a href="javascript:void(0)" onclick="onCreate(0)" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom" id="btn--add-new">
                    <i class="fa fa-plus"></i> <span>Thêm mới</span>
                </a>
            </div>
        </div>
        @Html.Partial("_SearchPartial")
        <div class="widge-t-body">
            <div id="tbl-ThuTuc" class="hntbl-cover vanban_chung_box">
                <table class="hinet-table table table-striped table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="width30">STT</th>
                            <th>Thời gian</th>
                            <th>Nội dung</th>
                            <th>Địa điểm</th>
                            <th>Thành phần tham dự</th>
                            <th>Duyệt</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="pd0 hienthi_vanban customize-hinet-table"></div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="total-page" value="@Model.TotalPage" />
<input type="hidden" id="total-record" value="@Model.Count" />
<script>
    var groupData = eval(@groupData);
</script>
<script src="~/Scripts/modules/lichcongtac/lichcongtac_index.js"></script>
<script>
    function CreateUnit() {
        $.ajax({
            type: "get",
            url: "/QLLichLamViecArea/QLLichLamViec/Create",
            success: function (rs) {
                $("#globalModal").html(rs);
                $("#globalModal").modal("show");
            }, error: function (er) {
                console.log(er);
            }
        })
    }
    $(document).ready(function () {

        $(".date-picker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true, yearRange: "-50:+20",
            showWeek: false, weekHeader: "Tuần",
            language: 'vi',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (date) {

            }
        });
    })
</script>

SourceCode/Web/Areas/QLLichLamViecArea/Views/QLLichLamViec/_CreatePartial.cshtml
@using mojoPortal.Web.Areas.QL_LichCongTacArea.Models

@model CreateVM
@{

}


<div class="modal-dialog" style="min-width:950px">
    @using (Ajax.BeginForm("Create", "QLLichLamViec", new { @area = "QLLichLamViecArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "createQL_LichCongTacForm" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Tạo mới lịch công tác</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="control-label col-sm-4">Ngày làm việc <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.NgayLamViec, new { @class = "form-control date-picker" })
                            @Html.ValidationMessageFor(m => m.NgayLamViec, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Thời gian bắt đầu <span class="red">*</span></label>
                        <div class="col-sm-8">
                            <div class="col-sm-6 text-center" style="padding-left:0px">
                                @Html.DropDownListFor(m => m.Gio, Model.ListDropdownGio, new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(m => m.Gio, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-sm-6 text-center" style="padding-right:0px">
                                @Html.DropDownListFor(m => m.Phut, Model.ListDropdownPhut, new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(m => m.Phut, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-sm-4">Nội dung <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextAreaFor(m => m.NoiDung, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NoiDung, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Địa điểm <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextAreaFor(m => m.DiaDiem, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.DiaDiem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Thành phần tham dự <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.ThanhPhanThamDuArray, Model.ListThanhPhanThamDu, new { @class = "form-control select2", @multiple = "@multiple" })
                            @Html.ValidationMessageFor(m => m.ThanhPhanThamDuArray, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Duyệt? <span class="red"></span></label>
                        <div class="col-sm-8">
                            <input type="checkbox" name="IsPublish" />
                            @Html.ValidationMessageFor(m => m.IsPublish, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer center">

                <button type="button" onclick="SubmitForm()" id="btnSubmit" class="btn btn-primary">Hoàn thành</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery/AdditionValidation.js"></script>
<script src="/Scripts/jquery/jquery.validate.unobtrusive.min.js"></script>
<script>
    function SubmitForm() {
        var oke = jQuery('#createQL_LichCongTacForm').valid();
        if (oke) {
            $("#btnSubmit").prop("disabled", false);

            // Get form
            var form = $('#createQL_LichCongTacForm')[0];

            // Create an FormData object
            var data = new FormData(form);
            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                url: "/QLLichLamViecArea/QLLichLamViec/Create",
                data: data,
                processData: false,
                contentType: false,
                cache: false,
                timeout: 600000,
                success: function (data) {
                    onAjaxSubmitSuccess(data);
                },
                error: function (e) {

                    console.log("ERROR : ", e);

                }
            });

        }

    }


    $(document).ready(function () {

        $(".date-picker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true, yearRange: "-50:+20",
            showWeek: false, weekHeader: "Tuần",
            language: 'vi',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (date) {

            }
        });
        $(".select2").select2();
    })
</script>

SourceCode/Web/Areas/QLLichLamViecArea/Views/QLLichLamViec/_EditPartial.cshtml
@using mojoPortal.Web.Areas.QL_LichCongTacArea.Models

@model EditVM
@{

}
<div class="modal-dialog" style="min-width:950px">
    @using (Ajax.BeginForm("Edit", "QLLichLamViec", new { @area = "QLLichLamViecArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "onAjaxSubmitSuccess",
    }, new { id = "createQL_LichCongTacForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="center">
                    <h4 class="modal-title">Cập nhật Quản lý lịch công tác</h4>
                </div>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.HiddenFor(x => x.ItemID)
                    <div class="form-group">
                        <label class="control-label col-sm-4">Ngày làm việc <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.NgayLamViec, string.Format("{0:dd/MM/yyyy}", Model.NgayLamViec), new { @class = "form-control date-picker" })
                            @Html.ValidationMessageFor(m => m.NgayLamViec, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Thời gian bắt đầu <span class="red">*</span></label>
                        <div class="col-sm-8">
                            <div class="col-sm-6 text-center" style="padding-left:0px">
                                @Html.DropDownListFor(m => m.Gio, Model.ListDropdownGio, new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(m => m.Gio, "", new { @class = "text-danger" })
                            </div>
                            <div class="col-sm-6 text-center" style="padding-right:0px">
                                @Html.DropDownListFor(m => m.Phut, Model.ListDropdownPhut, new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(m => m.Phut, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Nội dung <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextAreaFor(m => m.NoiDung, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NoiDung, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Địa điểm <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.TextAreaFor(m => m.DiaDiem, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.DiaDiem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Thành phần tham dự <span class="red">*</span></label>
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.ThanhPhanThamDuArray, Model.ListThanhPhanThamDu, new { @class = "form-control select2", @multiple = "@multiple" })
                            @Html.ValidationMessageFor(m => m.ThanhPhanThamDuArray, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-4">Duyệt? <span class="red"></span></label>
                        <div class="col-sm-8">
                            <input type="checkbox" name="IsPublish" @(Model.IsPublish ? "checked" : "") />
                            @Html.ValidationMessageFor(m => m.IsPublish, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer center">
                <button type="button" onclick="SubmitForm()" id="btnSubmit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery/AdditionValidation.js"></script>
<script src="/Scripts/jquery/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        var thanhTD = '@Model.ThanhPhanThamDu';
        console.log(thanhTD);
        if (thanhTD) {
            var split = thanhTD.split(' ');
            for (var i = 0; i < split.length; i++) {
                $("#ThanhPhanThamDuArray option[value='" + split[i] + "']").prop("selected", true);
            }
        }
      
    })
    function SubmitForm() {
        var oke = jQuery('#createQL_LichCongTacForm').valid();
        if (oke) {
            $("#btnSubmit").prop("disabled", false);

            // Get form
            var form = $('#createQL_LichCongTacForm')[0];

            // Create an FormData object
            var data = new FormData(form);
            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                url: "/QLLichLamViecArea/QLLichLamViec/Edit",
                data: data,
                processData: false,
                contentType: false,
                cache: false,
                timeout: 600000,
                success: function (data) {
                    onAjaxSubmitSuccess(data);
                },
                error: function (e) {

                    console.log("ERROR : ", e);

                }
            });

        }

    }
    $(document).ready(function () {

        $(".date-picker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true, yearRange: "-50:+20",
            showWeek: false, weekHeader: "Tuần",
            language: 'vi',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (date) {

            }
        });
        $(".select2").select2();
    })
</script>

SourceCode/Web/Areas/QLLichLamViecArea/Views/QLLichLamViec/_SearchPartial.cshtml
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well SearchBox">

        @using (Ajax.BeginForm("searchData", "QLLichLamViec", new { Area = "QLLichLamViecArea" },
            new AjaxOptions()
            {
                HttpMethod = "POST",
                OnFailure = "AjaxFormError",
                OnSuccess = "AjaxSearchSuccess",
            }, new {id="frmSearch" }))

        {
            @Html.AntiForgeryToken()

            <div class="row row-block">
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label">Lãnh đạo</div>
                    <div class="col-md-8">
                        @Html.DropDownList("IdLanhDaoFilter", ViewBag.ListLanhDao as List<SelectListItem>, "--Vui lòng chọn--", new { @class = "form-control select2" })
                    </div>
                </div>

                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label">Ngày làm việc</div>
                    <div class="col-md-8">
                        <input class="form-control width100 date-picker" type="text" name="NgayLamViecFilter" />
                    </div>
                </div>
                <div class="col-md-12 center" style=" margin-top:20px;">
                    <button id="btnSearch" type="button" onclick="SearchForm()" class="btn btn-labeled btn-primary btn-sm">

                        Tìm kiếm
                    </button>
                    <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger btn-sm">

                        Đóng
                    </a>
                </div>
            </div>

        }
    </div>
</div>

<script>
    function SearchForm() {

            // Get form
        var form = $('#frmSearch')[0];

            // Create an FormData object
            var data = new FormData(form);
            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                url: "/QLLichLamViecArea/QLLichLamViec/searchData",
                data: data,
                processData: false,
                contentType: false,
                cache: false,
                timeout: 600000,
                success: function (rs) {
                        $("#tbl-ThuTuc").hinetTable("data", {
                            pageIndex: 1,
                            pagecount: rs.TotalPage,
                            recordCount: rs.Count,
                            listItem: rs.ListItem,
                        });
                },
                error: function (e) {

                    console.log("ERROR : ", e);

                }
            });
    }

</script>