SourceCode/Web/Areas/DanhMucArea/Controllers/DanhMucController.cs
using mojoPortal.Service.Business;
using mojoPortal.Web.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mojoPortal.Model.Data;
using mojoportal.Service.CommonBusiness;
using mojoportal.CoreHelpers;
using mojoPortal.Service.CommonModel.coreDanhMuc;
using mojoPortal.Web.Areas.DanhMucArea.Models;

namespace mojoPortal.Web.Areas.DanhMucArea.Controllers
{
    public class DanhMucController : BaseController
    {
        // GET: DanhMucArea/DanhMuc
        public DanhMucController()
        {
            core_DanhMucBusiness = Get<core_DanhMucBusiness>();

        }
        // GET: BaoCaoArea/BaoCaoArea
        public PartialViewResult FormDanhMuc(int id = 0)
        {
            var model = new DanhMucVM();
            if (id > 0)
            {
              var  core_DanhMuc = core_DanhMucBusiness.Find(id);
                if (core_DanhMuc == null)
                {
                    throw new Exception("Không tìm thấy dữ liệu");
                }
                model = MapDataHelper<DanhMucVM, core_DanhMuc>.MapData(core_DanhMuc);

            }
            return PartialView("_FormDanhMuc", model);
        }

        [HttpPost]
        public JsonResult SaveForm(DanhMucVM model, FormCollection formCollection)
        {
            var result = new JsonResultBO(true);
            var report = new core_DanhMuc();
            try
            {
                result.Message = "Thêm mới chuyên mục thành công";

                report = new core_DanhMuc();
                if (model.ItemID > 0)
                {
                    report = core_DanhMucBusiness.Find(model.ItemID);
                    result.Message = "Cập nhật thông tin chuyên mục thành công";
                }
                else
                {
                    report.CreatedByUser = siteUser.UserId;
                    report.CreatedDate = DateTime.Now;
                    report.SiteID = siteSettings.SiteId;
                }
                //get rewrite url product
                report = MaperData.MapAllowNull<core_DanhMuc, DanhMucVM>(report, model);
                report.IsPublish = formCollection["IsPublish"].ToBooleanOnOff();
                core_DanhMucBusiness.Save(report);
            }
            catch (Exception ex)
            {
                result.Message = "Không thể thực hiện thao tác này";
                result.Status = false;
            }
            return Json(result);
        }



        [HttpPost]
        public JsonResult Delete(int id)
        {
            var result = new JsonResultBO(true);
            try
            {
                result.Message = "Xóa báo chuyên mục liên kết thành công";
                core_DanhMucBusiness.Delete(id);
                core_DanhMucBusiness.context.SaveChanges();
            }
            catch (Exception ex)
            {
                result.Message = "Không thực hiện được thao tác này";
                result.Status = false;
            }
            return Json(result);
        }


        public ActionResult Index()
        {

           var   data = core_DanhMucBusiness.GetDaTaByPage(null);
            var searchModel = new core_DanhMucSearchBO();
            searchModel.pageIndex = 1;
            searchModel.pageSize = 20;
            SessionManager.SetValue("danhMucSearchModel", searchModel);
            return View(data);
        }

        [HttpPost]
        public JsonResult GetData(int pageIndex, string sortQuery, int pageSize)
        {
            var searchModel =
                (core_DanhMucSearchBO)SessionManager.GetValue("danhMucSearchModel");
            if (searchModel == null) searchModel = new core_DanhMucSearchBO();
            searchModel.pageIndex = pageIndex;
            searchModel.pageSize = pageSize;
            searchModel.sortQuery = sortQuery;

            SessionManager.SetValue("BaoCaoSearchModel", searchModel);
            var data = core_DanhMucBusiness.GetDaTaByPage(searchModel, pageIndex, pageSize);
            return Json(data);
        }
        [HttpPost]

        public JsonResult SearchData(core_DanhMucSearchBO searchModel)
        {
            if (searchModel is null)
            {
                throw new ArgumentNullException(nameof(searchModel));
            }

            var search =
         (core_DanhMucSearchBO)SessionManager.GetValue("danhMucSearchModel");
            search = MapDataHelper<core_DanhMucSearchBO, core_DanhMucSearchBO>.MapData(searchModel);

            SessionManager.SetValue("danhMucSearchModel", search);
            var data = core_DanhMucBusiness.GetDaTaByPage(search, 1, searchModel.pageSize);
            data.PageIndex = 1;
            data.PageSize = 20;
            return Json(data);
        }
    }
}

SourceCode/Web/Areas/DanhMucArea/Views/DanhMuc/Index.cshtml
@using Newtonsoft.Json
@using mojoportal.Service.CommonBusiness
@using mojoPortal.Service.CommonModel.coreDanhMuc
@model PageListResultBO<core_DanhMucBO>
@{
    Layout = "~/Views/Shared/_LayoutAjaxEmpty.cshtml";
    ViewBag.Title = "Quản lý chuyên mục liên kết";
    var groupData = Html.Raw(JsonConvert.SerializeObject(Model.ListItem));
}


<div id="content">
    <div class="content__main_table table_admin">
        <div class="wf100 titleDanhsach listvanban__box_admin">
            <h2>Quản lý chuyên mục liên kết</h2>
        </div>
        <div class="listvanban__box__thaotac wf100">
            <div class="rowthaotac__left listvanban__box__thaotac__row col-sm-6 pd0">
                <a href="#collapseDiv" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom collapsed" aria-controls="collapsePanel" data-toggle="collapse" role="button">
                    <i class="fa fa-search"></i>  <span>Tìm kiếm</span>
                </a>
                <a href="javascript:void(0)" onclick="onEdit(0)" class="btn listvanban__box__thaotac__btn hvr-sweep-to-bottom" id="btn--add-new">
                    <i class="fa fa-plus"></i> <span>Thêm mới</span>
                </a>               
            </div>
        </div>
        @Html.Partial("_SearchPartial")
        <div class="widge-t-body">
            <div id="tbl-BaoCao" class="hntbl-cover vanban_chung_box">
                <table class="hinet-table table table-striped table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="width30">STT</th>
                            <th>Tiêu đề</th>
                            <th>Đường dẫn</th>
                            <th>Mô tả</th>
                            <th>Thứ tự</th>
                            <th>Hiển thị</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
                <div class="pd0 hienthi_vanban customize-hinet-table"></div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="total-page" value="@Model.TotalPage" />
<input type="hidden" id="total-record" value="@Model.Count" />
<script>
    var groupData = eval(@groupData);
</script>
<script src="~/Scripts/modules/danhMuc/danhmuc_index.js"></script>
<script>
    function CreateUnit() {
        $.ajax({
            type: "get",
            url: "/DanhMucArea/DanhMuc/FormDanhMuc",
            success: function (rs) {
                $("#globalModal").html(rs);
                $("#globalModal").modal("show");
            }, error: function (er) {
                console.log(er);
            }
        })
    }
</script>

SourceCode/Web/Areas/DanhMucArea/Views/DanhMuc/_FormDanhMuc.cshtml
@using Newtonsoft.Json
@using mojoPortal.Web.Areas.DanhMucArea.Models
@model DanhMucVM
@{
    ViewBag.Title = "Quản lý chuyên mục liên kết";

    var title = "Thêm mới chuyên mục liên kết";

    if (Model.ItemID > 0)
    {
        title = "Cập nhật chuyên mục liên kết";

    }

    //var groupData = Html.Raw(JsonConvert.SerializeObject(Model.PageData));
}
<style>
    .form-group {
        margin-bottom: 10px;
        display: flex;
        align-items: center;
        flex-wrap: wrap;
    }

    #fileList {
        margin-left: 18%;
    }

    .acb {
        width: 50%;
    }

    .acb1 {
        width: -50%;
    }

    #frmReport .col-sm-4 {
        padding-left: 15px;
        padding-right: 15px;
    }
</style>
@using (
Ajax.BeginForm("SaveForm", "DanhMuc",
new AjaxOptions { HttpMethod = "POST", OnSuccess = "ccc", OnFailure = "AjaxError" },
new { @class = "", id = "frmReport", area = "DanhMucArea" }))
{
    @Html.HiddenFor(x => x.ItemID)

    <div class="modal-dialog" style="width:1000px;max-width:100%">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">@title</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">

                <div class="form-horizontal">
                    <h3 class="legend-title">Thông tin chuyên mục liên kết</h3>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Tiêu đề<span class="red">*</span></label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Title)

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Đường dẫn<span class="red">*</span></label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(x => x.UrlLink, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.UrlLink)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Mô tả</label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(x => x.Sapo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Sapo)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2">Thứ tự hiển thị</label>
                        <div class="col-sm-4">

                            @Html.TextBoxFor(x => x.OrderBy, new { @class = "form-control", @type = "number" })
                            @Html.ValidationMessageFor(x => x.OrderBy)
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label  col-sm-2" for="IsPublished">Hiển thị</label>
                        <div class="col-sm-4">
                            <input type="checkbox" id="IsPublish" name="IsPublish" @(Model.IsPublish == true ? "checked" : Model.ItemID == 0 ? "checked" : "") />
                        </div>
                    </div>

                </div>

            </div>
            <div class="modal-footer center boder-box">
                <button type="button" onclick="SubmitForm()" class="btn btn-primary">Hoàn thành</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-sign-out" aria-hidden="true"></i> <span>Đóng</span>
                </button>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery/AdditionValidation.js"></script>
<script src="/Scripts/jquery/jquery.validate.unobtrusive.min.js"></script>


<script>

    function SubmitForm() {
        debugger;
        var oke = jQuery('#frmReport').valid();
        if (oke) {
            $("#frmReport").submit();
        }
    }
    $(document).ready(function () {
        $(".select2").select2();
        $(".txt-picker").datepicker({
            dateFormat: 'dd/mm/yy',
            changeMonth: true,
            changeYear: true, yearRange: "-50:+20",
            showWeek: false, weekHeader: "Tuần",
            language: 'vi',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (date) {

            }
        });
    });

    function ccc(rs) {
        if (rs.Status == true) {
            reloadTable();
            NotifySuccess(rs.Message);
            CloseGlobalModal();
        } else {
            NotifyError(rs.Message);
        }
    }




</script>

SourceCode/Web/Areas/DanhMucArea/Views/DanhMuc/_SearchPartial.cshtml
<style>
    .row-block {
        margin: 5px 0px;
        display: flex;
    }

    .txt-label {
        padding-top: 7px;
    }

    .width100 {
        width: 100% !important;
    }
</style>
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well">

        @using (Ajax.BeginForm("searchData", "DanhMuc",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "failure",
        OnSuccess = "searchSuccess",
    }, new { area = "DanhMucArea", id="frmSearchReport" }))
        {
            @Html.AntiForgeryToken()
            <div class="row row-block">
                <div class="col-md-6 row-block">
                    <div class="col-md-4 txt-label control-label">Tiêu đề</div>
                    <div class="col-md-8">
                        <input class="form-control width100" type="text" name="TitleFilter" />
                    </div>
                </div>
                <div class="col-md-12 center" style=" margin-top:20px;">
                    <button id="btnSearch" type="button" onclick="SearchSubmit()" class="btn btn-labeled btn-primary">
                        <span class="btn-label">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </span>
                        Tìm kiếm
                    </button>

                    <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger">
                        <span class="btn-label"><i class="fa fa-sign-out" aria-hidden="true"></i></span>
                        Đóng
                    </a>
                </div>
            </div>

        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")
<script>
    function SearchSubmit() {
        $("#frmSearchReport").submit();
    }
    function searchSuccess(rs) {
        $("#tbl-BaoCao").hinetTable("data", {
            pageIndex: 1,
            pagecount: rs.TotalPage,
            recordCount: rs.Count,
            listItem: rs.ListItem,
        });
    }
    function pagefunctionSearch() {
        $(".txt-select2").select2();
    }
</script>